# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('genre', models.TextField()),
                ('status', models.TextField()),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
