# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='genre',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='status',
            field=models.CharField(max_length=32),
        ),
    ]
